FROM apache/spark-py:latest

# copiamos el conector de mongo para spark dentro de la imagen que ya existe de apache/spark
COPY mongo-spark-connector_2.12-10.5.0-all.jar /opt/spark/jars/
COPY aws-java-sdk-bundle-1.11.375.jar /opt/spark/jars/
COPY hadoop-aws-3.3.1.jar /opt/spark/jars/

